### PR TITLE
Fix typo so nomads uses nomads skin

### PR DESCRIPTION
**Pull request by TheKeyBlue**
for issue #20

### CODE REVIEW

**Comment by CookieNoob** [comment]
these inconsistent naming conventions... 

the units have the tag "NOMAD" and the skin is "nomads"... xD this causes some errors in the unit manager as well (it tried to filter for "nomads" when it was supposed to be "nomad")

**Comment by Exotic-Retard** [comment]
yeah i noticed this too
we need to decide on a standard and stick to it i think.

we can either opt to go for one all the time or for a mix of both under specific conditions.

however, i reckon the most sensible thing is to always go for nomads.
because other factions are always AEON or w.e. and it can be used as plural so that should be the official name of the faction "Nomads"

we should just agree to do that then refactor probably one thing at a time to avoid any broken shit, or maybe do a find > replace in files and put out the fire? xD

**Comment by TheKeyBlue** [comment]
Using nomads always does seem most sensible.
Having to know what these specific conditions are would just be an extra hurdle for development, imo.

**Comment by CookieNoob** [comment]
I dont like these inconsistent naming either, however changing it by just replacing the string will lead to problems as some of the occurrences are in file paths, so we need to adjust the file names too.

**Pull request merged**
